export const reviewRepository = {
	getReviewOptions: () => {
		return {
			1: [
				"PUNCTUALITY",
				"TRAVEL_SAFETY",
				"COMFORT",
				"CLEANLINESS",
				"TRAVEL_SPEED",
				"APPLICATION_SERVICE",
				"NUMBER_OF_SEATS",
				"TRAVEL_ROUTE",
				"NUMBER_OF_STOPS",
			],
			2: [
				"PUNCTUALITY",
				"TRAVEL_SAFETY",
				"COMFORT",
				"CLEANLINESS",
				"TRAVEL_SPEED",
				"APPLICATION_SERVICE",
				"NUMBER_OF_SEATS",
				"TRAVEL_ROUTE",
				"NUMBER_OF_STOPS",
			],
			3: [
				"PUNCTUALITY",
				"TRAVEL_SAFETY",
				"COMFORT",
				"CLEANLINESS",
				"TRAVEL_SPEED",
				"APPLICATION_SERVICE",
				"NUMBER_OF_SEATS",
				"TRAVEL_ROUTE",
				"NUMBER_OF_STOPS",
			],
			4: [
				"PUNCTUALITY",
				"TRAVEL_SAFETY",
				"COMFORT",
				"CLEANLINESS",
				"TRAVEL_SPEED",
				"APPLICATION_SERVICE",
				"NUMBER_OF_SEATS",
				"TRAVEL_ROUTE",
				"NUMBER_OF_STOPS",
			],
			5: [
				"PUNCTUALITY",
				"TRAVEL_SAFETY",
				"COMFORT",
				"CLEANLINESS",
				"APPLICATION_SERVICE",
			],
		};
	},
};
